# Generated by Django 3.2 on 2021-05-05 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census_api', '0002_rename_citizens_citizen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='name',
        ),
    ]
