# Generated by Django 3.1.9 on 2021-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census_api', '0003_remove_citizen_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citizen',
            old_name='sure_name',
            new_name='sur_name',
        ),
        migrations.AlterField(
            model_name='citizen',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
